//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


namespace BigCommerce.RestApi.Core
{
    ///// <remarks/>
    //[DataContract]
    //public partial class Addresses
    //{

    //    private List<Address> itemsField;

    //    /// <remarks/>
    //    [DataMember]
    //    public List<Address> Items
    //    {
    //        get
    //        {
    //            return this.itemsField;
    //        }
    //        set
    //        {
    //            this.itemsField = value;
    //        }
    //    }
    //}

    [DataContract]
    public partial class Address
    {

        private string idField;

        private string order_idField;

        private string first_nameField;

        private string last_nameField;

        private string companyField;

        private string street_1Field;

        private string street_2Field;

        private string cityField;

        private string zipField;

        private string countryField;

        private string country_iso2Field;

        private string stateField;

        private string emailField;

        private string phoneField;

        private string items_totalField;

        private string items_shippedField;

        private string shipping_methodField;

        private string base_costField;

        private string cost_ex_taxField;

        private string cost_inc_taxField;

        private string cost_taxField;

        private string cost_tax_class_idField;

        private string base_handling_costField;

        private string handling_cost_ex_taxField;

        private string handling_cost_inc_taxField;

        private string handling_cost_taxField;

        private string handling_cost_tax_class_idField;

        private string shipping_zone_idField;

        private string shipping_zone_nameField;

        /// <remarks/>
        [DataMember]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string order_id
        {
            get
            {
                return this.order_idField;
            }
            set
            {
                this.order_idField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string first_name
        {
            get
            {
                return this.first_nameField;
            }
            set
            {
                this.first_nameField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string last_name
        {
            get
            {
                return this.last_nameField;
            }
            set
            {
                this.last_nameField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string company
        {
            get
            {
                return this.companyField;
            }
            set
            {
                this.companyField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string street_1
        {
            get
            {
                return this.street_1Field;
            }
            set
            {
                this.street_1Field = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string street_2
        {
            get
            {
                return this.street_2Field;
            }
            set
            {
                this.street_2Field = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string zip
        {
            get
            {
                return this.zipField;
            }
            set
            {
                this.zipField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string country_iso2
        {
            get
            {
                return this.country_iso2Field;
            }
            set
            {
                this.country_iso2Field = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string items_total
        {
            get
            {
                return this.items_totalField;
            }
            set
            {
                this.items_totalField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string items_shipped
        {
            get
            {
                return this.items_shippedField;
            }
            set
            {
                this.items_shippedField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string shipping_method
        {
            get
            {
                return this.shipping_methodField;
            }
            set
            {
                this.shipping_methodField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string base_cost
        {
            get
            {
                return this.base_costField;
            }
            set
            {
                this.base_costField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string cost_ex_tax
        {
            get
            {
                return this.cost_ex_taxField;
            }
            set
            {
                this.cost_ex_taxField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string cost_inc_tax
        {
            get
            {
                return this.cost_inc_taxField;
            }
            set
            {
                this.cost_inc_taxField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string cost_tax
        {
            get
            {
                return this.cost_taxField;
            }
            set
            {
                this.cost_taxField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string cost_tax_class_id
        {
            get
            {
                return this.cost_tax_class_idField;
            }
            set
            {
                this.cost_tax_class_idField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string base_handling_cost
        {
            get
            {
                return this.base_handling_costField;
            }
            set
            {
                this.base_handling_costField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string handling_cost_ex_tax
        {
            get
            {
                return this.handling_cost_ex_taxField;
            }
            set
            {
                this.handling_cost_ex_taxField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string handling_cost_inc_tax
        {
            get
            {
                return this.handling_cost_inc_taxField;
            }
            set
            {
                this.handling_cost_inc_taxField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string handling_cost_tax
        {
            get
            {
                return this.handling_cost_taxField;
            }
            set
            {
                this.handling_cost_taxField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string handling_cost_tax_class_id
        {
            get
            {
                return this.handling_cost_tax_class_idField;
            }
            set
            {
                this.handling_cost_tax_class_idField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string shipping_zone_id
        {
            get
            {
                return this.shipping_zone_idField;
            }
            set
            {
                this.shipping_zone_idField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string shipping_zone_name
        {
            get
            {
                return this.shipping_zone_nameField;
            }
            set
            {
                this.shipping_zone_nameField = value;
            }
        }
    }
}