//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 

namespace BigCommerce.RestApi.Core
{

    [DataContract]
    public partial class link
    {

        private string relField;

        private string hrefField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rel
        {
            get
            {
                return this.relField;
            }
            set
            {
                this.relField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string href
        {
            get
            {
                return this.hrefField;
            }
            set
            {
                this.hrefField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    [DataContract]
    public partial class order
    {

        private string idField;

        private string customer_idField;

        private string date_createdField;

        private string date_modifiedField;

        private string date_shippedField;

        private string status_idField;

        private string statusField;

        private string subtotal_ex_taxField;

        private string subtotal_inc_taxField;

        private string subtotal_taxField;

        private string base_shipping_costField;

        private string shipping_cost_ex_taxField;

        private string shipping_cost_inc_taxField;

        private string shipping_cost_taxField;

        private string shipping_cost_tax_class_idField;

        private string base_handling_costField;

        private string handling_cost_ex_taxField;

        private string handling_cost_inc_taxField;

        private string handling_cost_taxField;

        private string handling_cost_tax_class_idField;

        private string base_wrapping_costField;

        private string wrapping_cost_ex_taxField;

        private string wrapping_cost_inc_taxField;

        private string wrapping_cost_taxField;

        private string wrapping_cost_tax_class_idField;

        private string total_ex_taxField;

        private string total_inc_taxField;

        private string total_taxField;

        private string items_totalField;

        private string items_shippedField;

        private string payment_methodField;

        private string payment_provider_idField;

        private string payment_statusField;

        private string refunded_amountField;

        private string order_is_digitalField;

        private string store_credit_amountField;

        private string gift_certificate_amountField;

        private string ip_addressField;

        private string geoip_countryField;

        private string geoip_country_iso2Field;

        private string currency_idField;

        private string currency_codeField;

        private string currency_exchange_rateField;

        private string default_currency_idField;

        private string default_currency_codeField;

        private string staff_notesField;

        private string customer_messageField;

        private string discount_amountField;

        private string coupon_discountField;

        private string shipping_address_countField;

        private string is_deletedField;

        private string order_sourceField;

        private string external_sourceField;

        private orderBilling_address billing_addressField;

        private link[][] productsField;

        private link[][] shipping_addressesField;

        private link[][] couponsField;

        /// <remarks/>
        [DataMember]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string customer_id
        {
            get
            {
                return this.customer_idField;
            }
            set
            {
                this.customer_idField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string date_created
        {
            get
            {
                return this.date_createdField;
            }
            set
            {
                this.date_createdField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string date_modified
        {
            get
            {
                return this.date_modifiedField;
            }
            set
            {
                this.date_modifiedField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string date_shipped
        {
            get
            {
                return this.date_shippedField;
            }
            set
            {
                this.date_shippedField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string status_id
        {
            get
            {
                return this.status_idField;
            }
            set
            {
                this.status_idField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string subtotal_ex_tax
        {
            get
            {
                return this.subtotal_ex_taxField;
            }
            set
            {
                this.subtotal_ex_taxField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string subtotal_inc_tax
        {
            get
            {
                return this.subtotal_inc_taxField;
            }
            set
            {
                this.subtotal_inc_taxField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string subtotal_tax
        {
            get
            {
                return this.subtotal_taxField;
            }
            set
            {
                this.subtotal_taxField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string base_shipping_cost
        {
            get
            {
                return this.base_shipping_costField;
            }
            set
            {
                this.base_shipping_costField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string shipping_cost_ex_tax
        {
            get
            {
                return this.shipping_cost_ex_taxField;
            }
            set
            {
                this.shipping_cost_ex_taxField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string shipping_cost_inc_tax
        {
            get
            {
                return this.shipping_cost_inc_taxField;
            }
            set
            {
                this.shipping_cost_inc_taxField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string shipping_cost_tax
        {
            get
            {
                return this.shipping_cost_taxField;
            }
            set
            {
                this.shipping_cost_taxField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string shipping_cost_tax_class_id
        {
            get
            {
                return this.shipping_cost_tax_class_idField;
            }
            set
            {
                this.shipping_cost_tax_class_idField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string base_handling_cost
        {
            get
            {
                return this.base_handling_costField;
            }
            set
            {
                this.base_handling_costField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string handling_cost_ex_tax
        {
            get
            {
                return this.handling_cost_ex_taxField;
            }
            set
            {
                this.handling_cost_ex_taxField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string handling_cost_inc_tax
        {
            get
            {
                return this.handling_cost_inc_taxField;
            }
            set
            {
                this.handling_cost_inc_taxField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string handling_cost_tax
        {
            get
            {
                return this.handling_cost_taxField;
            }
            set
            {
                this.handling_cost_taxField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string handling_cost_tax_class_id
        {
            get
            {
                return this.handling_cost_tax_class_idField;
            }
            set
            {
                this.handling_cost_tax_class_idField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string base_wrapping_cost
        {
            get
            {
                return this.base_wrapping_costField;
            }
            set
            {
                this.base_wrapping_costField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string wrapping_cost_ex_tax
        {
            get
            {
                return this.wrapping_cost_ex_taxField;
            }
            set
            {
                this.wrapping_cost_ex_taxField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string wrapping_cost_inc_tax
        {
            get
            {
                return this.wrapping_cost_inc_taxField;
            }
            set
            {
                this.wrapping_cost_inc_taxField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string wrapping_cost_tax
        {
            get
            {
                return this.wrapping_cost_taxField;
            }
            set
            {
                this.wrapping_cost_taxField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string wrapping_cost_tax_class_id
        {
            get
            {
                return this.wrapping_cost_tax_class_idField;
            }
            set
            {
                this.wrapping_cost_tax_class_idField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string total_ex_tax
        {
            get
            {
                return this.total_ex_taxField;
            }
            set
            {
                this.total_ex_taxField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string total_inc_tax
        {
            get
            {
                return this.total_inc_taxField;
            }
            set
            {
                this.total_inc_taxField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string total_tax
        {
            get
            {
                return this.total_taxField;
            }
            set
            {
                this.total_taxField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string items_total
        {
            get
            {
                return this.items_totalField;
            }
            set
            {
                this.items_totalField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string items_shipped
        {
            get
            {
                return this.items_shippedField;
            }
            set
            {
                this.items_shippedField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string payment_method
        {
            get
            {
                return this.payment_methodField;
            }
            set
            {
                this.payment_methodField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string payment_provider_id
        {
            get
            {
                return this.payment_provider_idField;
            }
            set
            {
                this.payment_provider_idField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string payment_status
        {
            get
            {
                return this.payment_statusField;
            }
            set
            {
                this.payment_statusField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string refunded_amount
        {
            get
            {
                return this.refunded_amountField;
            }
            set
            {
                this.refunded_amountField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string order_is_digital
        {
            get
            {
                return this.order_is_digitalField;
            }
            set
            {
                this.order_is_digitalField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string store_credit_amount
        {
            get
            {
                return this.store_credit_amountField;
            }
            set
            {
                this.store_credit_amountField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string gift_certificate_amount
        {
            get
            {
                return this.gift_certificate_amountField;
            }
            set
            {
                this.gift_certificate_amountField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string ip_address
        {
            get
            {
                return this.ip_addressField;
            }
            set
            {
                this.ip_addressField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string geoip_country
        {
            get
            {
                return this.geoip_countryField;
            }
            set
            {
                this.geoip_countryField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string geoip_country_iso2
        {
            get
            {
                return this.geoip_country_iso2Field;
            }
            set
            {
                this.geoip_country_iso2Field = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string currency_id
        {
            get
            {
                return this.currency_idField;
            }
            set
            {
                this.currency_idField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string currency_code
        {
            get
            {
                return this.currency_codeField;
            }
            set
            {
                this.currency_codeField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string currency_exchange_rate
        {
            get
            {
                return this.currency_exchange_rateField;
            }
            set
            {
                this.currency_exchange_rateField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string default_currency_id
        {
            get
            {
                return this.default_currency_idField;
            }
            set
            {
                this.default_currency_idField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string default_currency_code
        {
            get
            {
                return this.default_currency_codeField;
            }
            set
            {
                this.default_currency_codeField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string staff_notes
        {
            get
            {
                return this.staff_notesField;
            }
            set
            {
                this.staff_notesField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string customer_message
        {
            get
            {
                return this.customer_messageField;
            }
            set
            {
                this.customer_messageField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string discount_amount
        {
            get
            {
                return this.discount_amountField;
            }
            set
            {
                this.discount_amountField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string coupon_discount
        {
            get
            {
                return this.coupon_discountField;
            }
            set
            {
                this.coupon_discountField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string shipping_address_count
        {
            get
            {
                return this.shipping_address_countField;
            }
            set
            {
                this.shipping_address_countField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string is_deleted
        {
            get
            {
                return this.is_deletedField;
            }
            set
            {
                this.is_deletedField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string order_source
        {
            get
            {
                return this.order_sourceField;
            }
            set
            {
                this.order_sourceField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string external_source
        {
            get
            {
                return this.external_sourceField;
            }
            set
            {
                this.external_sourceField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public orderBilling_address billing_address
        {
            get
            {
                return this.billing_addressField;
            }
            set
            {
                this.billing_addressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("link", typeof(link))]
        public link[][] products
        {
            get
            {
                return this.productsField;
            }
            set
            {
                this.productsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("link", typeof(link))]
        public link[][] shipping_addresses
        {
            get
            {
                return this.shipping_addressesField;
            }
            set
            {
                this.shipping_addressesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("link", typeof(link))]
        public link[][] coupons
        {
            get
            {
                return this.couponsField;
            }
            set
            {
                this.couponsField = value;
            }
        }
    }

    [DataContract]
    public partial class orderBilling_address
    {

        private string first_nameField;

        private string last_nameField;

        private string companyField;

        private string street_1Field;

        private string street_2Field;

        private string cityField;

        private string stateField;

        private string zipField;

        private string countryField;

        private string country_iso2Field;

        private string phoneField;

        private string emailField;

        /// <remarks/>
        [DataMember]
        public string first_name
        {
            get
            {
                return this.first_nameField;
            }
            set
            {
                this.first_nameField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string last_name
        {
            get
            {
                return this.last_nameField;
            }
            set
            {
                this.last_nameField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string company
        {
            get
            {
                return this.companyField;
            }
            set
            {
                this.companyField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string street_1
        {
            get
            {
                return this.street_1Field;
            }
            set
            {
                this.street_1Field = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string street_2
        {
            get
            {
                return this.street_2Field;
            }
            set
            {
                this.street_2Field = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string zip
        {
            get
            {
                return this.zipField;
            }
            set
            {
                this.zipField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string country_iso2
        {
            get
            {
                return this.country_iso2Field;
            }
            set
            {
                this.country_iso2Field = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
    }

    [DataContract]
    public partial class NewDataSet
    {

        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("link", typeof(link), IsNullable = true)]
        [System.Xml.Serialization.XmlElementAttribute("order", typeof(order))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
}