//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
//[DataContract]
//public partial class products
//{

//    private List<Product> itemsField;

//    /// <remarks/>
//    [DataMember]
//    public List<Product> Items
//    {
//        get
//        {
//            return this.itemsField;
//        }
//        set
//        {
//            this.itemsField = value;
//        }
//    }
//}

/// <remarks/>
[DataContract]
public partial class Product
{

    private string idField;

    private string order_idField;

    private string product_idField;

    private string order_address_idField;

    private string nameField;

    private string skuField;

    private string typeField;

    private string base_priceField;

    private string price_ex_taxField;

    private string price_inc_taxField;

    private string price_taxField;

    private string base_totalField;

    private string total_ex_taxField;

    private string total_inc_taxField;

    private string total_taxField;

    private string weightField;

    private string quantityField;

    private string base_cost_priceField;

    private string cost_price_inc_taxField;

    private string cost_price_ex_taxField;

    private string cost_price_taxField;

    private string is_refundedField;

    private string refund_amountField;

    private string return_idField;

    private string wrapping_nameField;

    private string base_wrapping_costField;

    private string wrapping_cost_ex_taxField;

    private string wrapping_cost_inc_taxField;

    private string wrapping_cost_taxField;

    private string wrapping_messageField;

    private string quantity_shippedField;

    private string event_nameField;

    private string event_dateField;

    private string fixed_shipping_costField;

    private string ebay_item_idField;

    private string ebay_transaction_idField;

    private string option_set_idField;

    private string parent_order_product_idField;

    private string is_bundled_productField;

    private string bin_picking_numberField;

    private List<applied_discounts> applied_discountsField;

    private List<product_options> product_optionsField;

    private string configurable_fieldsField;

    /// <remarks/>
    [DataMember]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string order_id
    {
        get
        {
            return this.order_idField;
        }
        set
        {
            this.order_idField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string product_id
    {
        get
        {
            return this.product_idField;
        }
        set
        {
            this.product_idField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string order_address_id
    {
        get
        {
            return this.order_address_idField;
        }
        set
        {
            this.order_address_idField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string sku
    {
        get
        {
            return this.skuField;
        }
        set
        {
            this.skuField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string base_price
    {
        get
        {
            return this.base_priceField;
        }
        set
        {
            this.base_priceField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string price_ex_tax
    {
        get
        {
            return this.price_ex_taxField;
        }
        set
        {
            this.price_ex_taxField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string price_inc_tax
    {
        get
        {
            return this.price_inc_taxField;
        }
        set
        {
            this.price_inc_taxField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string price_tax
    {
        get
        {
            return this.price_taxField;
        }
        set
        {
            this.price_taxField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string base_total
    {
        get
        {
            return this.base_totalField;
        }
        set
        {
            this.base_totalField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string total_ex_tax
    {
        get
        {
            return this.total_ex_taxField;
        }
        set
        {
            this.total_ex_taxField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string total_inc_tax
    {
        get
        {
            return this.total_inc_taxField;
        }
        set
        {
            this.total_inc_taxField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string total_tax
    {
        get
        {
            return this.total_taxField;
        }
        set
        {
            this.total_taxField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string weight
    {
        get
        {
            return this.weightField;
        }
        set
        {
            this.weightField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string quantity
    {
        get
        {
            return this.quantityField;
        }
        set
        {
            this.quantityField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string base_cost_price
    {
        get
        {
            return this.base_cost_priceField;
        }
        set
        {
            this.base_cost_priceField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string cost_price_inc_tax
    {
        get
        {
            return this.cost_price_inc_taxField;
        }
        set
        {
            this.cost_price_inc_taxField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string cost_price_ex_tax
    {
        get
        {
            return this.cost_price_ex_taxField;
        }
        set
        {
            this.cost_price_ex_taxField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string cost_price_tax
    {
        get
        {
            return this.cost_price_taxField;
        }
        set
        {
            this.cost_price_taxField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string is_refunded
    {
        get
        {
            return this.is_refundedField;
        }
        set
        {
            this.is_refundedField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string refund_amount
    {
        get
        {
            return this.refund_amountField;
        }
        set
        {
            this.refund_amountField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string return_id
    {
        get
        {
            return this.return_idField;
        }
        set
        {
            this.return_idField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string wrapping_name
    {
        get
        {
            return this.wrapping_nameField;
        }
        set
        {
            this.wrapping_nameField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string base_wrapping_cost
    {
        get
        {
            return this.base_wrapping_costField;
        }
        set
        {
            this.base_wrapping_costField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string wrapping_cost_ex_tax
    {
        get
        {
            return this.wrapping_cost_ex_taxField;
        }
        set
        {
            this.wrapping_cost_ex_taxField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string wrapping_cost_inc_tax
    {
        get
        {
            return this.wrapping_cost_inc_taxField;
        }
        set
        {
            this.wrapping_cost_inc_taxField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string wrapping_cost_tax
    {
        get
        {
            return this.wrapping_cost_taxField;
        }
        set
        {
            this.wrapping_cost_taxField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string wrapping_message
    {
        get
        {
            return this.wrapping_messageField;
        }
        set
        {
            this.wrapping_messageField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string quantity_shipped
    {
        get
        {
            return this.quantity_shippedField;
        }
        set
        {
            this.quantity_shippedField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string event_name
    {
        get
        {
            return this.event_nameField;
        }
        set
        {
            this.event_nameField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string event_date
    {
        get
        {
            return this.event_dateField;
        }
        set
        {
            this.event_dateField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string fixed_shipping_cost
    {
        get
        {
            return this.fixed_shipping_costField;
        }
        set
        {
            this.fixed_shipping_costField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string ebay_item_id
    {
        get
        {
            return this.ebay_item_idField;
        }
        set
        {
            this.ebay_item_idField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string ebay_transaction_id
    {
        get
        {
            return this.ebay_transaction_idField;
        }
        set
        {
            this.ebay_transaction_idField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string option_set_id
    {
        get
        {
            return this.option_set_idField;
        }
        set
        {
            this.option_set_idField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string parent_order_product_id
    {
        get
        {
            return this.parent_order_product_idField;
        }
        set
        {
            this.parent_order_product_idField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string is_bundled_product
    {
        get
        {
            return this.is_bundled_productField;
        }
        set
        {
            this.is_bundled_productField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public string bin_picking_number
    {
        get
        {
            return this.bin_picking_numberField;
        }
        set
        {
            this.bin_picking_numberField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public List<applied_discounts> applied_discounts
    {
        get
        {
            return this.applied_discountsField;
        }
        set
        {
            this.applied_discountsField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public List<product_options> product_options
    {
        get
        {
            return this.product_optionsField;
        }
        set
        {
            this.product_optionsField = value;
        }
    }

    /// <remarks/>
    //[DataMember]
    //public string configurable_fields
    //{
    //    get
    //    {
    //        return this.configurable_fieldsField;
    //    }
    //    set
    //    {
    //        this.configurable_fieldsField = value;
    //    }
    //}
}

[DataContract]
public partial class applied_discounts
{
    List<discounts> discountsField;

    [DataMember]
    public List<discounts> discounts
    {
        get
        {
            return this.discountsField;
        }
        set
        {
            this.discountsField = value;
        }
    }

}

[DataContract]
public partial class product_options
{
    List<options> optionsField;

    public List<options> options 
    {
        get
        {
            return this.optionsField;
        }
        set
        {
            this.optionsField = value;
        }
    }
}

[DataContract]
public partial class options
{
    private int idField;
    private int optionIdField;
    private int orderProductIdField;
    private string displayNameField;
    private string displayValueField;
    private string valueField;
    private string nameField;
    private string displayStyleField;

    [DataMember]
    public int id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    [DataMember]
    public int option_id
    {
        get
        {
            return this.optionIdField;
        }
        set
        {
            this.optionIdField = value;
        }
    }

    [DataMember]
    public int order_product_id
    {
        get
        {
            return this.orderProductIdField;
        }
        set
        {
            this.orderProductIdField = value;
        }
    }

    [DataMember]
    public string display_name
    {
        get
        {
            return this.displayNameField;
        }
        set
        {
            this.displayNameField = value;
        }
    }

    [DataMember]
    public string display_value
    {
        get
        {
            return this.displayValueField;
        }
        set
        {
            this.displayValueField = value;
        }
    }

    [DataMember]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }

    [DataMember]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    [DataMember]
    public string display_style
    {
        get
        {
            return this.displayStyleField;
        }
        set
        {
            this.displayStyleField = value;
        }
    }
}

[DataContract]
public partial class discounts
{
    private int idField;
    private decimal amountField;

    [DataMember]
    public int id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    [DataMember]
    public decimal amount
    {
        get
        {
            return this.amountField;
        }
        set
        {
            this.amountField = value;
        }
    }


}
